baseURL = "https://rioemdados.netlify.app/"
languageCode = "en-us"
title = "Rio em Dados: Covid-19"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Rio em Dados"
    description = "Este projeto é uma iniciativa independente de alguns profissionais da área da Estatística das instituições ENCE/IBGE e UFRJ voltado para o estudo de dados sobre a COVID-19 no estado do Rio de Janeiro."
    githubUsername = "#"
    accent = "darkorange"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    dateFormat = "02/01/2006"


    # path to the favicon, under "static"
    favicon = "favicon.ico"

[[menu.main]]
    url = "/"
    name = "Início"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "Sobre"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/equipe/"
    name = "Equipe"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


[[menu.icon]]
    url = "https://www.instagram.com/rioemdados/"
    name = "instagram"
    weight = 1
    
[[menu.icon]]
    url = "https://www.facebook.com/rioemdados-108797877647691"
    name = "facebook"
    weight = 2    

[[menu.icon]]
    url = "https://github.com/redcovid19"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "mailto:rioemdadoscovid@gmail.com"
    name = "envelope-o"
    weight = 4
